import Foundation

/// Fallback park data for offline/demo use when the server is unavailable.
/// These are real Fairfax County parks with accurate amenity information.
enum DemoData {
    static let parks: [Park] = [
        makePark(
            name: "Clemyjontri Park",
            classification: "Special Interest Park",
            address: "6317 Georgetown Pike",
            city: "McLean",
            description: "Inclusive playground designed for children of all abilities. Features a carousel, sensory-friendly areas, and fully accessible equipment.",
            playground: "Yes - Inclusive/Accessible",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "Paved paths",
            parking: "Large lot",
            waterActivities: "Spray ground (seasonal)",
            specialFeatures: ["Inclusive Playground", "Carousel", "Sensory Garden", "Accessible Equipment"],
            dogFriendly: "No",
            bestFor: ["Toddlers", "Special Needs", "Families"],
            lat: 38.9547, lng: -77.1847,
            momScore: 4.8, totalReviews: 42
        ),
        makePark(
            name: "Burke Lake Park",
            classification: "Countywide Park",
            address: "7315 Ox Road",
            city: "Fairfax Station",
            description: "Large park surrounding Burke Lake with a miniature train, carousel, disc golf, fishing, and extensive trails.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes - Multiple",
            trails: "5+ miles",
            parking: "Multiple lots",
            waterActivities: "Fishing, Boat Rental",
            specialFeatures: ["Miniature Train", "Carousel", "Disc Golf", "Fishing Pier", "Ice Cream Shop"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Families", "Fishing", "Nature Walks"],
            lat: 38.7608, lng: -77.2997,
            momScore: 4.6, totalReviews: 87
        ),
        makePark(
            name: "Lake Fairfax Park",
            classification: "Countywide Park",
            address: "1400 Lake Fairfax Drive",
            city: "Reston",
            description: "Water Mine water park, skate park, playground, camping, and lake activities.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "2+ miles",
            parking: "Large lot",
            waterActivities: "Water Mine Water Park, Lake",
            specialFeatures: ["Water Mine Water Park", "Skate Park", "Campground", "Boat Rental"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Water Play", "Camping", "Summer Fun"],
            lat: 38.9647, lng: -77.3386,
            momScore: 4.5, totalReviews: 63
        ),
        makePark(
            name: "Huntley Meadows Park",
            classification: "Natural Resource Park",
            address: "3701 Lockheed Blvd",
            city: "Alexandria",
            description: "Premier wetland park with boardwalk trail, wildlife observation, and nature center.",
            playground: "No",
            restrooms: "Yes",
            picnicShelters: "No",
            trails: "Boardwalk + 3 miles",
            parking: "Moderate lot",
            waterActivities: "None",
            specialFeatures: ["Boardwalk Trail", "Wildlife Observation", "Nature Center", "Birdwatching"],
            dogFriendly: "No",
            bestFor: ["Nature Walks", "Birdwatching", "Education"],
            lat: 38.7561, lng: -77.1019,
            momScore: 4.3, totalReviews: 31
        ),
        makePark(
            name: "Riverbend Park",
            classification: "Natural Resource Park",
            address: "8700 Potomac Hills St",
            city: "Great Falls",
            description: "Scenic Potomac River access with hiking trails, kayak launch, and nature center.",
            playground: "No",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "10+ miles",
            parking: "Moderate lot",
            waterActivities: "Kayak Launch, River Access",
            specialFeatures: ["Potomac River Access", "Kayak Launch", "Nature Center"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Hiking", "Kayaking", "Nature"],
            lat: 38.9985, lng: -77.2519,
            momScore: 4.4, totalReviews: 28
        ),
        makePark(
            name: "Chantilly Park",
            classification: "Community Park",
            address: "4000 Walney Road",
            city: "Chantilly",
            description: "Large community park with multiple playgrounds, sports fields, and a nature trail.",
            playground: "Yes - Multiple",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "1.5 miles",
            parking: "Large lot",
            waterActivities: "None",
            specialFeatures: ["Multiple Playgrounds", "Sports Fields", "Nature Trail"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Playgrounds", "Sports", "Families"],
            lat: 38.8764, lng: -77.4311,
            momScore: 4.1, totalReviews: 19
        ),
        makePark(
            name: "Frying Pan Farm Park",
            classification: "Special Interest Park",
            address: "2709 West Ox Road",
            city: "Herndon",
            description: "Working farm with animals, playground, carousel, and seasonal events.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "Short paths",
            parking: "Large lot",
            waterActivities: "None",
            specialFeatures: ["Farm Animals", "Carousel", "Country Store", "Seasonal Events"],
            dogFriendly: "No",
            bestFor: ["Toddlers", "Farm Animals", "Education"],
            lat: 38.9225, lng: -77.3508,
            momScore: 4.7, totalReviews: 55
        ),
        makePark(
            name: "Ellanor C. Lawrence Park",
            classification: "Natural Resource Park",
            address: "5040 Walney Road",
            city: "Chantilly",
            description: "Historic and natural resource park with Walney Visitor Center, hiking trails, and Cabell's Mill.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "5+ miles",
            parking: "Moderate lot",
            waterActivities: "Stream access",
            specialFeatures: ["Visitor Center", "Cabell's Mill", "Historic Sites"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Hiking", "History", "Nature"],
            lat: 38.8700, lng: -77.4183,
            momScore: 4.2, totalReviews: 22
        ),
        makePark(
            name: "Lee District Park",
            classification: "District Park",
            address: "6601 Telegraph Road",
            city: "Franconia",
            description: "Large district park with RECenter, spray park, amphitheater, and extensive recreation facilities.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes - Multiple",
            trails: "2 miles",
            parking: "Large lot",
            waterActivities: "Spray Park",
            specialFeatures: ["Spray Park", "RECenter", "Amphitheater", "Treehouse"],
            dogFriendly: "Yes - Dog Park",
            bestFor: ["Water Play", "Sports", "Dog Owners"],
            lat: 38.7639, lng: -77.0981,
            momScore: 4.4, totalReviews: 38
        ),
        makePark(
            name: "South Run District Park",
            classification: "District Park",
            address: "7550 Reservation Drive",
            city: "Springfield",
            description: "Wooded district park with RECenter, playground, and connections to Cross County Trail.",
            playground: "Yes",
            restrooms: "Yes",
            picnicShelters: "Yes",
            trails: "3+ miles",
            parking: "Moderate lot",
            waterActivities: "Indoor pool (RECenter)",
            specialFeatures: ["RECenter", "Cross County Trail Access", "Wooded Setting"],
            dogFriendly: "Yes - On leash",
            bestFor: ["Swimming", "Trails", "Playground"],
            lat: 38.7458, lng: -77.2611,
            momScore: 4.0, totalReviews: 15
        ),
    ]

    // MARK: - Helper to construct Park objects

    private static func makePark(
        name: String,
        classification: String,
        address: String,
        city: String,
        description: String,
        playground: String,
        restrooms: String,
        picnicShelters: String,
        trails: String,
        parking: String,
        waterActivities: String,
        specialFeatures: [String],
        dogFriendly: String,
        bestFor: [String],
        lat: Double,
        lng: Double,
        momScore: Double,
        totalReviews: Int
    ) -> Park {
        let jsonString = """
        {
            "park_name": "\(name)",
            "classification": "\(classification)",
            "address": "\(address)",
            "city": "\(city)",
            "description": "\(description)",
            "amenities": {
                "playground": "\(playground)",
                "restrooms": "\(restrooms)",
                "picnic_shelters": "\(picnicShelters)",
                "trails": "\(trails)",
                "parking": "\(parking)",
                "water_activities": "\(waterActivities)",
                "special_features": [\(specialFeatures.map { "\"\($0)\"" }.joined(separator: ","))],
                "dog_friendly": "\(dogFriendly)"
            },
            "best_for": [\(bestFor.map { "\"\($0)\"" }.joined(separator: ","))],
            "latitude": \(lat),
            "longitude": \(lng),
            "mom_score": \(momScore),
            "total_reviews": \(totalReviews)
        }
        """
        let data = jsonString.data(using: .utf8)!
        let decoder = JSONDecoder()
        return try! decoder.decode(Park.self, from: data)
    }
}
